--- 

- name: Install common dependencies
  yum: name={{ item }} state=installed
  with_items: 
    - ntp
    - libselinux-python
    - libsemanage-python
    - firewalld
  tags: ntp

- name: Configure the NTP file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp


